create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 80),
  email text not null unique
    check (email = lower(email) and char_length(email) <= 160 and email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  role text not null check (role in ('admin', 'checkin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_pin_sessions
  add column if not exists user_id uuid references public.admin_users(id) on delete cascade;

create index if not exists admin_pin_sessions_user_id_idx
  on public.admin_pin_sessions(user_id);

-- Sessions of the shared PIN belong to nobody; everyone signs in again by email.
delete from public.admin_pin_sessions where user_id is null;

create table if not exists public.admin_login_codes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.admin_users(id) on delete cascade,
  code_hash text not null,
  expires_at timestamptz not null,
  attempts smallint not null default 0,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists admin_login_codes_user_id_created_at_idx
  on public.admin_login_codes(user_id, created_at desc);

alter table public.admin_users enable row level security;
alter table public.admin_login_codes enable row level security;
revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.admin_login_codes from anon, authenticated;
