create table if not exists public.admin_pin_settings (
  id smallint primary key check (id = 1),
  pin_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_pin_sessions (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now()
);

create table if not exists public.admin_pin_attempts (
  id bigint generated by default as identity primary key,
  ip text not null,
  success boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists admin_pin_sessions_token_hash_idx
  on public.admin_pin_sessions(token_hash);

create index if not exists admin_pin_sessions_expires_at_idx
  on public.admin_pin_sessions(expires_at);

create index if not exists admin_pin_attempts_ip_created_at_idx
  on public.admin_pin_attempts(ip, created_at desc);

alter table public.admin_pin_settings enable row level security;
alter table public.admin_pin_sessions enable row level security;
alter table public.admin_pin_attempts enable row level security;

revoke all on table public.admin_pin_settings from anon, authenticated;
revoke all on table public.admin_pin_sessions from anon, authenticated;
revoke all on table public.admin_pin_attempts from anon, authenticated;
