-- The first, PIN-based version of 20261006150000_admin_users.sql already ran on the remote.
-- This brings that shape to the email sign-in one; on a fresh database it changes nothing.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'admin_users' and column_name = 'username'
  ) then
    -- PIN accounts have no email and cannot sign in anymore; the first admin is re-inserted by hand.
    delete from public.admin_users;
    alter table public.admin_users drop column username, drop column pin_hash;
    alter table public.admin_users add column email text not null unique
      check (email = lower(email) and char_length(email) <= 160 and email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$');
    alter table public.admin_users alter column created_at set default now();
  end if;
end $$;

create table if not exists public.admin_login_codes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.admin_users(id) on delete cascade,
  code_hash text not null,
  expires_at timestamptz not null,
  attempts smallint not null default 0,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists admin_login_codes_user_id_created_at_idx
  on public.admin_login_codes(user_id, created_at desc);

alter table public.admin_login_codes enable row level security;
revoke all on table public.admin_login_codes from anon, authenticated;
