alter table public.registrations add column if not exists pass_emailed_at timestamptz;

create table if not exists public.pass_email_codes (
  id bigint generated by default as identity primary key,
  registration_id uuid not null references public.registrations(id) on delete cascade,
  code_hash text not null,
  expires_at timestamptz not null,
  attempts smallint not null default 0,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists pass_email_codes_registration_id_created_at_idx
  on public.pass_email_codes(registration_id, created_at desc);

alter table public.pass_email_codes enable row level security;
revoke all on table public.pass_email_codes from anon, authenticated;
